<?php

namespace App\Filament\Seller\Resources\ProductResource\Pages;

use App\Enums\CategoryTypeEnum;
use App\Enums\LevelProductEnum;
use App\Enums\ProductActiveEnum;
use App\Filament\Seller\Resources\ProductResource;
use App\Helpers\ProductsHelper;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Filament\Support\Exceptions\Halt;

class CreateProduct extends CreateRecord
{
    protected static string $resource = ProductResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['user_id']=auth()->id();
        $data['city_id']=auth()->user()->city_id;
        $data['active']=ProductActiveEnum::PENDING->value;
        $data['level']=LevelProductEnum::NORMAL->value;
        $data['type']=CategoryTypeEnum::PRODUCT->value;
        $data['expert'] = \Str::words(strip_tags(html_entity_decode($data['info'])), 15);
        $plan = ProductsHelper::getPresentPlanActive();
        if ($plan == null) {
            throw new Halt('يرجى الإشتراك بخطة للنشر');
        }
        $isAvailableCreate=ProductsHelper::isAvailableCreateProduct($plan);
        if(!$isAvailableCreate){
            throw new Halt('لا يمكنك نشر المزيد خلال هذا الشهر يرجى ترقية الخطة لنشر المزيد');
        }
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
