<?php

namespace App\Filament\Seller\Resources\ProductResource\Pages;

use App\Filament\Seller\Resources\ProductResource;
use App\Models\Product;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditProduct extends EditRecord
{
    protected static string $resource = ProductResource::class;

    public function mount(int|string $record): void
    {
        parent::mount($record); parent::mount($record);
        $product=Product::find($record);
        abort_if($product->user_id !=auth()->id(),403,'غير مصرح لك بالدخول');

    }

    public static function canAccess(array $parameters = []): bool
{

    return parent::canAccess($parameters); // TODO: Change the autogenerated stub
}

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }
}
