<?php

namespace App\Filament\Seller\Resources\ProductResource\Pages;

use App\Filament\Seller\Resources\ProductResource;
use App\Models\Product;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditProduct extends EditRecord
{
    protected static string $resource = ProductResource::class;

    public function mount(int|string $record): void
    {
        parent::mount($record);
       if( Product::find($record)?->user_id!=auth()->id()){
           abort(404);
       }// TODO: Change the autogenerated stub
    }

    public static function canAccess(array $parameters = []): bool
{

    return parent::canAccess($parameters); // TODO: Change the autogenerated stub
}

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }
}
