<?php declare(strict_types=1);

namespace App\GraphQL\Validators;

use App\Enums\ProductActiveEnum;
use Illuminate\Validation\Rule;
use Nuwave\Lighthouse\Validation\Validator;

final class CreateProductValidator extends Validator
{
    /**
     * Return the validation rules.
     *
     * @return array<string, array<mixed>>
     */
    public function rules(): array
    {

        return [
            'name' => ['nullable', 'min:3'],//'nullable|min:3',
            'city_id' => ['required', 'exists:cities,id'],
            'main' => ['required', 'image'],
            'images' => ['nullable', 'array'],
            'images.*' => ['image'],
            'video' => ['nullable', 'string'],
            'info' => ['string', 'min:5'],
            'tags' => ['nullable', 'array'],
            'tags.*' => ['string'],
            'is_available' => ['boolean'],
            'price' => ['required', 'numeric', 'gt:0'],
            'is_discount' => ['boolean'],
            'discount' => [Rule::requiredIf(request()->is_discount == true), 'gt:0'],
            'category_id' => ['required', 'exists:categories,id'],
            'sub1_id' => ['required', 'exists:categories,id'],
            'sub2_id' => ['nullable', 'exists:categories,id'],
            'sub3_id' => ['nullable', 'exists:categories,id'],
            'sub4_id' => ['nullable', 'exists:categories,id'],
            'options' => ['nullable', 'array'],
            'write' => ['nullable', 'array'],
            'attribute' => ['nullable', 'array'],

        ];
    }

    public function messages(): array
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
