<?php

namespace App\Filament\Resources\ServiceResource\Pages;

use App\Enums\CategoryTypeEnum;
use App\Filament\Resources\ServiceResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateService extends CreateRecord
{
    protected static string $resource = ServiceResource::class;
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['expert'] = \Str::words(strip_tags(html_entity_decode($data['info'])), 15);
        $data['type'] = CategoryTypeEnum::SERVICE->value;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
