<?php

namespace App\Filament\Resources\ServiceResource\Pages;

use App\Enums\CategoryTypeEnum;
use App\Filament\Resources\ServiceResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditService extends EditRecord
{
    protected static string $resource = ServiceResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }
   protected function mutateFormDataBeforeSave(array $data): array
   {
       $data['expert'] = \Str::words(strip_tags(html_entity_decode($data['info'])), 15);
       return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
   }
}
