<?php

namespace App\Filament\Seller\Resources\JobResource\Pages;

use App\Filament\Seller\Resources\JobResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListJobs extends ListRecords
{
    protected static string $resource = JobResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

  protected function getTableQuery(): ?Builder
  {
      return parent::getTableQuery()->where('user_id',auth()->id())->job(); // TODO: Change the autogenerated stub
  }
}
