<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class RegisterRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return  [
            'name' => 'required|string|min:3',
            'email' => 'required|unique:users,email',
            'password' => 'required|min:8',
            'confirmPassword' => 'same:password',
            'phone' => 'required',
            'phone_code'=>'required|exists:countries,code',
            'city' => 'required|exists:cities,id',
            'address' => 'required|string',
        ];
    }

    public function messages()
    {
        return [
            'name.*' => 'يرجى إدخال اسم صالح',
            'email.required' => 'يرجى إدخال بريد إلكتروني صالح',
            'email.unique' => 'البريد الإلكتروني موجود بالفعل',
            'password.*' => 'يرجى إدخال كلمة مرور من 8 احرف على الأقل',
            'confirmPassword.*' => 'كلمة المرور غير متطابقة',
            'phone.*' => 'يرجى إدخال رقم هاتف',
            'phone_code.*' => 'يرجى تحديد الدولة',
            'city' => 'يرجى تحديد المدينة',
            'address' => 'يرجى إدخال عنوانك التفصيلي'
        ]; // TODO: Change the autogenerated stub
    }
}
