<?php

namespace App\Filament\Resources\MainCityResource\Pages;

use App\Filament\Resources\MainCityResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListMainCities extends ListRecords
{
    protected static string $resource = MainCityResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    protected function getTableQuery(): ?Builder
    {
        return parent::getTableQuery()->where('is_main',true); // TODO: Change the autogenerated stub
    }
}
