<?php

namespace App\Filament\Seller\Resources\TenderResource\Pages;

use App\Enums\ProductActiveEnum;
use App\Filament\Seller\Resources\TenderResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateTender extends CreateRecord
{
    protected static string $resource = TenderResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['user_id']=auth()->id();
        $data['active']=ProductActiveEnum::PENDING->value ;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
