<?php

namespace App\Filament\Resources\InvoiceResource\Pages;

use App\Enums\OrderStatusEnum;
use App\Filament\Resources\InvoiceResource;
use Filament\Actions;
use Filament\Resources\Components\Tab;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListInvoices extends ListRecords
{
    protected static string $resource = InvoiceResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    public function getTabs(): array
    {
        return [
            Tab::make('all')->modifyQueryUsing(fn($query)=>$query)->label('الكل'),
            Tab::make( OrderStatusEnum::PENDING->value)->modifyQueryUsing(fn($query)=>$query->where('status','pending'))->label(OrderStatusEnum::PENDING->getLabel()),
            Tab::make( OrderStatusEnum::AGREE->value)->modifyQueryUsing(fn($query)=>$query->where('status','agree'))->label(OrderStatusEnum::AGREE->getLabel()),
            Tab::make( OrderStatusEnum::AWAY->value)->modifyQueryUsing(fn($query)=>$query->where('status','away'))->label(OrderStatusEnum::AWAY->getLabel()),
            Tab::make( OrderStatusEnum::COMPLETE->value)->modifyQueryUsing(fn($query)=>$query->where('status','complete'))->label(OrderStatusEnum::COMPLETE->getLabel()),
            Tab::make( OrderStatusEnum::CANCELED->value)->modifyQueryUsing(fn($query)=>$query->where('status','canceled'))->label(OrderStatusEnum::CANCELED->getLabel()),


        ];
    }

    protected function getTableQuery(): ?Builder
    {
        return parent::getTableQuery()->with('seller','user')->latest(); // TODO: Change the autogenerated stub
    }
}
