<?php

namespace App\Filament\Resources\InvoiceResource\Pages;

use App\Enums\OrderStatusEnum;
use App\Filament\Resources\InvoiceResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListInvoices extends ListRecords
{
    protected static string $resource = InvoiceResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    public function getTabs(): array
    {
        return [
            'الكل'=>fn($query)=>$query,
            OrderStatusEnum::PENDING->value=>fn($query)=>$query->where('status','pending'),
            OrderStatusEnum::AGREE->value=>fn($query)=>$query->where('status','agree'),
            OrderStatusEnum::AWAY->value=>fn($query)=>$query->where('status','away'),
            OrderStatusEnum::COMPLETE->value=>fn($query)=>$query->where('status','complete'),
            OrderStatusEnum::CANCELED->value=>fn($query)=>$query->where('status','canceled'),
        ];
    }

    protected function getTableQuery(): ?Builder
    {
        return parent::getTableQuery()->with('seller','user')->latest(); // TODO: Change the autogenerated stub
    }
}
