<?php

namespace App\Filament\Resources\UserResource\RelationManagers;

use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class BalancesRelationManager extends RelationManager
{
    protected static string $relationship = 'balances';

    protected function canCreate(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    protected function canEdit(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('credit')->label('ايداع'),
                Forms\Components\TextInput::make('debit')->label('سحب'),
                Forms\Components\TextInput::make('info')->label('الوصف')
                    ->required()
                    ->maxLength(255),
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->modifyQueryUsing(fn($query)=>$query->latest())
            ->recordTitleAttribute('info')
            ->columns([
                Tables\Columns\TextColumn::make('credit')->label('ايداع'),
                Tables\Columns\TextColumn::make('debit')->label('سحب'),
                Tables\Columns\TextColumn::make('info')->label('الوصف'),
                Tables\Columns\TextColumn::make('total')->label('الرصيد الحالي'),
                Tables\Columns\TextColumn::make('created_at')->date('Y-m-d')->label('تاريخ الحركة'),
            ])
            ->filters([
                //
            ])
            ->headerActions([
                Tables\Actions\CreateAction::make(),
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }
}
