<?php

namespace App\Filament\Resources\UserResource\RelationManagers;

use App\Enums\CommunityTypeEnum;
use App\Filament\Resources\CommunityResource;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class CommunitiesRelationManager extends RelationManager
{
    protected static string $relationship = 'communities';
protected function canCreate(): bool
{
    return false; // TODO: Change the autogenerated stub
}
protected function canEdit(Model $record): bool
{
    return false; // TODO: Change the autogenerated stub
}

protected function canDelete(Model $record): bool
{
    return false; // TODO: Change the autogenerated stub
}
protected function canDeleteAny(): bool
{
    return false; // TODO: Change the autogenerated stub
}

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('name')
                    ->required()
                    ->maxLength(255),
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->modifyQueryUsing(fn($query)=>$query->whereNot('type',CommunityTypeEnum::LIVE->value))
            ->recordTitleAttribute('name')
            ->columns([
                Tables\Columns\TextColumn::make('name')->url(fn($record)=>CommunityResource::getUrl('edit',['record'=>$record->id]),true),
                Tables\Columns\TextColumn::make('type')->formatStateUsing(fn($state)=>CommunityTypeEnum::tryFrom($state)->getLabel())->color(fn($state)=>CommunityTypeEnum::tryFrom($state)->getColor())
                    ->icon(fn($state)=>CommunityTypeEnum::tryFrom($state)->getIcon())
                    ->url(fn($record)=>CommunityResource::getUrl('edit',['record'=>$record->id]),true),
            ])
            ->filters([
                //
            ])
            ->headerActions([
                Tables\Actions\CreateAction::make(),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }
}
