<?php

namespace App\Filament\Resources\UserResource\RelationManagers;

use App\Models\Plan;
use App\Models\User;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class PlansRelationManager extends RelationManager
{
    protected static string $relationship = 'plans';

    protected function canCreate(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }



    protected function canDelete(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Select::make('plan_id')->options(Plan::pluck('name', 'id'))->label('الخطة'),
                Forms\Components\DatePicker::make('expired_date')->label('تاريخ إنتهاء الإشتراك'),
                Forms\Components\DatePicker::make('subscription_date')->label('تاريخ إنتهاء الإشتراك'),
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('name')
            ->columns([
             Tables\Columns\TextColumn::make('name'),
             Tables\Columns\TextColumn::make('subscription_date'),
             Tables\Columns\TextColumn::make('expired_date')

            ])
            ->filters([
                //
            ])
            ->headerActions([
                Tables\Actions\CreateAction::make(),
                Tables\Actions\Action::make('plans')->form([
                    Forms\Components\Select::make('plan_id')->options(Plan::pluck('name', 'id'))->label('الخطة'),
                    Forms\Components\DatePicker::make('expired_date')->label('تاريخ إنتهاء الإشتراك'),
                ])->action(function ($data, $livewire) {
                    /**
                     * @var $user User
                     */
                    $user = $livewire->ownerRecord;
                    $user->plans()->syncWithPivotValues($data['plan_id'], ['expired_date' => $data['expired_date'], 'subscription_date' => now()], false);
                    Notification::make('success')->title('نجاح العملية')->body('تم الإشتراك بالخطة')->success()->send();
                })
                    ->label('إشترك بخطة جديدة')
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }
}
