<?php

namespace App\Filament\Seller\Resources\ServiceResource\Pages;

use App\Enums\CategoryTypeEnum;
use App\Filament\Seller\Resources\ServiceResource;
use App\Helpers\ProductsHelper;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Filament\Support\Exceptions\Halt;
use Illuminate\Support\Str;

class CreateService extends CreateRecord
{
    protected static string $resource = ServiceResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['user_id']=auth()->id();
        $data['city_id']=auth()->user()->city_id;
        $data['expert'] = Str::words(strip_tags(html_entity_decode($data['info'])), 15);
        $data['type'] = CategoryTypeEnum::SERVICE->value;
        $plan = ProductsHelper::getPresentPlanActive();
        if ($plan == null) {
            throw new Halt('يرجى الإشتراك بخطة للنشر');
        }
        $isAvailableCreate=ProductsHelper::isAvailableCreateProduct($plan);
        if(!$isAvailableCreate){
            throw new Halt('لا يمكنك نشر المزيد خلال هذا الشهر يرجى ترقية الخطة لنشر المزيد');
        }
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
