<?php

namespace App\Filament\Widgets;

use App\Enums\CategoryTypeEnum;
use App\Enums\OrderStatusEnum;
use App\Models\Invoice;
use App\Models\Order;
use App\Models\Product;
use App\Models\User;
use Filament\Widgets\ChartWidget;
use Flowframe\Trend\Trend;
use Flowframe\Trend\TrendValue;

/*class InvoiceChart extends ChartWidget
{
   // protected static ?string $heading = 'طلبات الشحن';
    public static function canView(): bool
    {
        return auth()->user()->hasAllPermissions('widget_OrdersChart'); // TODO: Change the autogenerated stub
    }
    protected function getFilters(): ?array
    {
        return [
            'year' => 'هذه السنة',
            'back' => 'السنة السابقة',
            '360' => 'آخر 360 يوم',
            'today' => 'اليوم',
            'week' => 'آخر 7 أيام',
            'month' => 'هذا الشهر',
            '28' => 'آخر 28 يوم',
            '60' => 'آخر 60 يوم',

        ];
    }

    protected function getData(): array
    {
        $activeFilter = $this->filter;
        $start = now()->startOfYear();
        $end = now();
        $per = "perMonth";
        if ($activeFilter == 'week') {
            $start = now()->subDays(7);
            $per = "perDay";
        } elseif ($activeFilter == '28') {
            $start = now()->subDays(28);
            $per = "perDay";
        }elseif ($activeFilter == '60') {
            $start = now()->subDays(60);
            $per = "perWeek";
        } else if ($activeFilter == 'month') {
            $start = now()->startOfMonth();
            $per = "perWeek";
        } else if ($activeFilter == 'year') {
            $start = now()->startOfYear();

        } else if ($activeFilter == 'today') {
            $start = now()->startOfDay();
            $per = "perHour";
        } else if ($activeFilter == '360') {
            $start = now()->subYear();
            $per = "perMonth";
        } else if ($activeFilter == 'back') {
            $start = now()->startOfYear()->subYear();
            $end = now()->startOfYear()->subYear()->endOfYear();
            $per = "perMonth";
        }

        $invoiceComplete = Trend::query(Invoice::where('status',OrderStatusEnum::COMPLETE->value))
            ->between(
                start:$start ,
                end: $end,
            )
            ->$per()
            ->count();

        $invoiceCanceled = Trend::query(Invoice::where('status',OrderStatusEnum::CANCELED->value))
            ->between(
                start:$start ,
                end: $end,
            )
            ->$per()
            ->count();
        $invoiceAgree = Trend::query(Invoice::where('status',OrderStatusEnum::AGREE->value))
            ->between(
                start:$start ,
                end: $end,
            )
            ->$per()
            ->count();
        $invoicePending = Trend::query(Invoice::where('status',OrderStatusEnum::PENDING->value))
            ->between(
                start:$start ,
                end: $end,
            )
            ->$per()
            ->count();
        return [
            'datasets' => [
                [
                    'label' => 'طلبات الشحن بالإنتظار',
                    'data' => $invoicePending->map(fn (TrendValue $value) => $value->aggregate),
                    'backgroundColor' => '#99CDDD',
                    'borderColor' => '#99CDDD',
                ],
                [
                    'label' => 'طلبات الشحن تم الموافقة',
                    'data' => $invoiceAgree->map(fn (TrendValue $value) => $value->aggregate),
                    'backgroundColor' => '#99FFDD',
                    'borderColor' => '#99FFDD',
                ],
                [
                    'label' => 'طلبات الشحن  المكتملة',
                    'data' => $invoiceComplete->map(fn (TrendValue $value) => $value->aggregate),
                    'backgroundColor' => '#99FF00',
                    'borderColor' => '#99FF00',
                ],
                [
                    'label' => 'طلبات الشحن  الملغية',
                    'data' => $invoiceCanceled->map(fn (TrendValue $value) => $value->aggregate),
                    'backgroundColor' => '#FF9900',
                    'borderColor' => '#FF9900',
                ],

            ],
            'labels' =>  $invoiceComplete->map(fn (TrendValue $value) => $value->date),
        ];
    }

    protected function getType(): string
    {
        return 'bar';
    }
}*/
class InvoiceChart extends ChartWidget
{
    protected static ?string $heading = 'نسبة حالات الشراء';

    public static function canView(): bool
    {
        return auth()->user()->hasAllPermissions('widget_OrdersChart');
    }

    protected function getFilters(): ?array
    {
        return [
            '28' => 'آخر 28 يوم',
            'year' => 'هذه السنة',
            'back' => 'السنة السابقة',
            '360' => 'آخر 360 يوم',
            'today' => 'اليوم',
            'week' => 'آخر 7 أيام',
            'month' => 'هذا الشهر',

            '60' => 'آخر 60 يوم',
        ];
    }

    protected function getData(): array
    {
        $activeFilter = $this->filter;
        $start = now()->subDays(28);
        $end = now();

        if ($activeFilter == 'week') {
            $start = now()->subDays(7);
        } elseif ($activeFilter == '28') {
            $start = now()->subDays(28);
        } elseif ($activeFilter == '60') {
            $start = now()->subDays(60);
        } elseif ($activeFilter == 'month') {
            $start = now()->startOfMonth();
        } elseif ($activeFilter == 'year') {
            $start = now()->startOfYear();
        } elseif ($activeFilter == 'today') {
            $start = now()->startOfDay();
        } elseif ($activeFilter == '360') {
            $start = now()->subYear();
        } elseif ($activeFilter == 'back') {
            $start = now()->startOfYear()->subYear();
            $end = now()->startOfYear()->subYear()->endOfYear();
        }

        // حساب المجموع لكل حالة
        $invoicePending = Invoice::where('status', OrderStatusEnum::PENDING->value)
            ->whereBetween('created_at', [$start, $end])
            ->count();

        $invoiceAgree = Invoice::where('status', OrderStatusEnum::AGREE->value)
            ->whereBetween('created_at', [$start, $end])
            ->count();

        $invoiceComplete = Invoice::where('status', OrderStatusEnum::COMPLETE->value)
            ->whereBetween('created_at', [$start, $end])
            ->count();

        $invoiceCanceled = Invoice::where('status', OrderStatusEnum::CANCELED->value)
            ->whereBetween('created_at', [$start, $end])
            ->count();

        // تجهيز البيانات لمخطط Pie
        return [
            'datasets' => [
                [
                    'label' => 'حالات الشراء',
                    'data' => [
                        $invoicePending,
                        $invoiceAgree,
                        $invoiceComplete,
                        $invoiceCanceled,
                    ],
                    'backgroundColor' => [
                        '#99CDDD', // انتظار
                        '#99FFDD', // موافقة
                        '#99FF00', // مكتملة
                        '#FF9900', // ملغاة
                    ],
                    'hoverOffset' => 15,
                ],
            ],
            'labels' => [
                'بالإنتظار',
                'تمت الموافقة',
                'مكتملة',
                'ملغاة',
            ],
        ];
    }

    protected function getType(): string
    {
        return 'pie';
    }
}
