<?php

namespace App\Filament\Widgets;

use App\Enums\CategoryTypeEnum;
use App\Enums\OrderStatusEnum;
use App\Models\Invoice;
use App\Models\Order;
use App\Models\Product;
use App\Models\User;
use Filament\Widgets\ChartWidget;
use Flowframe\Trend\Trend;
use Flowframe\Trend\TrendValue;

class OrdersChart extends ChartWidget
{
   // protected static ?string $heading = 'طلبات الشحن';
    public static function canView(): bool
    {
        return auth()->user()->hasAllPermissions('widget_OrdersChart'); // TODO: Change the autogenerated stub
    }
    protected function getFilters(): ?array
    {
        return [
            'year' => 'هذه السنة',
            'back' => 'السنة السابقة',
            '360' => 'آخر 360 يوم',
            'today' => 'اليوم',
            'week' => 'آخر 7 أيام',
            'month' => 'هذا الشهر',
            '28' => 'آخر 28 يوم',
            '60' => 'آخر 60 يوم',

        ];
    }

    protected function getData(): array
    {
        $activeFilter = $this->filter;
        $start = now()->startOfYear();
        $end = now();
        $per = "perMonth";
        if ($activeFilter == 'week') {
            $start = now()->subDays(7);
            $per = "perDay";
        } elseif ($activeFilter == '28') {
            $start = now()->subDays(28);
            $per = "perDay";
        }elseif ($activeFilter == '60') {
            $start = now()->subDays(60);
            $per = "perWeek";
        } else if ($activeFilter == 'month') {
            $start = now()->startOfMonth();
            $per = "perWeek";
        } else if ($activeFilter == 'year') {
            $start = now()->startOfYear();

        } else if ($activeFilter == 'today') {
            $start = now()->startOfDay();
            $per = "perHour";
        } else if ($activeFilter == '360') {
            $start = now()->subYear();
            $per = "perMonth";
        } else if ($activeFilter == 'back') {
            $start = now()->startOfYear()->subYear();
            $end = now()->startOfYear()->subYear()->endOfYear();
            $per = "perMonth";
        }
        $ordersComplete = Trend::query(Order::where('status',OrderStatusEnum::COMPLETE->value))
 ->between(
                start:$start ,
                end: $end,
            )
            ->perMonth()
            ->count();
        $invoiceComplete = Trend::query(Invoice::where('status',OrderStatusEnum::COMPLETE->value))
            ->between(
                start:$start ,
                end: $end,
            )
            ->$per()
            ->count();
        $ordersCanceled = Trend::query(Order::where('status',OrderStatusEnum::CANCELED->value))
            ->between(
                start:$start ,
                end: $end,
            )
            ->$per()
            ->count();
        $invoiceCanceled = Trend::query(Invoice::where('status',OrderStatusEnum::CANCELED->value))
            ->between(
                start:$start ,
                end: $end,
            )
            ->$per()
            ->count();
        return [
            'datasets' => [
                [
                    'label' => 'طلبات الشحن الخاصة المكتملة',
                    'data' => $ordersComplete->map(fn (TrendValue $value) => $value->aggregate),
                    'backgroundColor' => '#00FF00',
                    'borderColor' => '#00FF00',
                ],
                [
                    'label' => 'طلبات الشحن الخاصة الملغية',
                    'data' => $ordersCanceled->map(fn (TrendValue $value) => $value->aggregate),
                    'backgroundColor' => '#FF0000',
                    'borderColor' => '#FF0000',
                ],
                [
                    'label' => 'طلبات الشحن للمنتجات المكتملة',
                    'data' => $invoiceComplete->map(fn (TrendValue $value) => $value->aggregate),
                    'backgroundColor' => '#99FF00',
                    'borderColor' => '#99FF00',
                ],
                [
                    'label' => 'طلبات الشحن للمنتجات الملغية',
                    'data' => $invoiceCanceled->map(fn (TrendValue $value) => $value->aggregate),
                    'backgroundColor' => '#FF9900',
                    'borderColor' => '#FF9900',
                ],

            ],
            'labels' =>  $invoiceComplete->map(fn (TrendValue $value) => $value->date),
        ];
    }

    protected function getType(): string
    {
        return 'bar';
    }
}
