<?php

namespace App\Filament\Widgets;

use App\Enums\CategoryTypeEnum;
use App\Models\Product;
use App\Models\User;
use Filament\Widgets\ChartWidget;
use Flowframe\Trend\Trend;
use Flowframe\Trend\TrendValue;

class RegisteredUserChart extends ChartWidget
{
  //  protected static ?string $heading = 'المسجلين الجدد';
    public static function canView(): bool
    {
        return auth()->user()->hasAllPermissions('widget_RegisteredUserChart'); // TODO: Change the autogenerated stub
    }
    protected function getFilters(): ?array
    {
        return [
            'year' => 'هذه السنة',
            'back' => 'السنة السابقة',
            '360' => 'آخر 360 يوم',
            'today' => 'اليوم',
            'week' => 'آخر 7 أيام',
            'month' => 'هذا الشهر',
            '28' => 'آخر 28 يوم',
            '60' => 'آخر 60 يوم',

        ];
    }

    protected function getData(): array
    {
        $activeFilter = $this->filter;
        $start = now()->startOfYear();
        $end = now();
        $per = "perMonth";
        if ($activeFilter == 'week') {
            $start = now()->subDays(7);
            $per = "perDay";
        } elseif ($activeFilter == '28') {
            $start = now()->subDays(28);
            $per = "perDay";
        }elseif ($activeFilter == '60') {
            $start = now()->subDays(60);
            $per = "perWeek";
        } else if ($activeFilter == 'month') {
            $start = now()->startOfMonth();
            $per = "perWeek";
        } else if ($activeFilter == 'year') {
            $start = now()->startOfYear();

        } else if ($activeFilter == 'today') {
            $start = now()->startOfDay();
            $per = "perHour";
        } else if ($activeFilter == '360') {
            $start = now()->subYear();
            $per = "perMonth";
        } else if ($activeFilter == 'back') {
            $start = now()->startOfYear()->subYear();
            $end = now()->startOfYear()->subYear()->endOfYear();
            $per = "perMonth";
        }
        $users = Trend::model(User::class)
 ->between(
                start:$start ,
                end: $end,
            )
            ->$per()
            ->count();
        return [
            'datasets' => [
                [
                    'label' => 'المسجلين الجدد',
                    'data' => $users->map(fn (TrendValue $value) => $value->aggregate),
                    'backgroundColor' => '#1e40af',
                    'borderColor' => '#0000cc',
                ],

            ],
            'labels' =>  $users->map(fn (TrendValue $value) => $value->date),
        ];
    }

    protected function getType(): string
    {
        return 'line';
    }
}
