<?php

namespace App\Filament\Widgets;

use App\Enums\CategoryTypeEnum;
use App\Models\Product;
use App\Models\ProductView;
use DB;
use Filament\Widgets\ChartWidget;
use Flowframe\Trend\Trend;
use Flowframe\Trend\TrendValue;

class SeeProductChart extends ChartWidget
{
   // protected static ?string $heading = 'إحصائيات المنشورات';

    public static function canView(): bool
    {
        return auth()->user()->hasAllPermissions('widget_CreatedProductChart'); // TODO: Change the autogenerated stub
    }

    protected function getFilters(): ?array
    {
        return [
            'year' => 'هذه السنة',
            'today' => 'اليوم',
            'week' => 'آخر 7 أيام',
            'month' => 'هذا الشهر',

        ];
    }

    protected function getData(): array
    {
        $activeFilter = $this->filter;
       $start=now()->startOfYear();
       $end=now();
       if($activeFilter=='week'){
           $start=now()->subDays(7);

       }else if($activeFilter=='month'){
            $start=now()->startOfMonth();

        }else if($activeFilter=='year'){
           $start=now()->startOfYear();

       }else if($activeFilter=='today'){
           $start=now()->startOfDay();

       }
        $products =  Trend::query(Product::query() ->whereIn('type', [
            CategoryTypeEnum::PRODUCT->value,
            CategoryTypeEnum::RESTAURANT->value,
        ])
            ->whereHas('views', function ($query) use ($start, $end) {
                $query->whereBetween('product_views.view_at', [$start, $end]);
            }))

            ->between(
                start: $start,
                end: $end,
            )
            ->perMonth()
            ->count();
        $tender = Trend::query(Product::query() ->whereIn('type', [
            CategoryTypeEnum::PRODUCT->value,
            CategoryTypeEnum::RESTAURANT->value,
        ])
            ->whereHas('views', function ($query) use ($start, $end) {
                $query->whereBetween('product_views.view_at', [$start, $end]);
            }))

            ->between(
                start: $start,
                end: $end,
            )
            ->perMonth()
            ->count();
        $job =Trend::query(Product::query() ->whereIn('type', [
            CategoryTypeEnum::PRODUCT->value,
            CategoryTypeEnum::RESTAURANT->value,
        ])
            ->whereHas('views', function ($query) use ($start, $end) {
                $query->whereBetween('product_views.view_at', [$start, $end]);
            }))

            ->between(
                start: $start,
                end: $end,
            )
            ->perMonth()
            ->count();
        return [
            'datasets' => [
                [
                    'label' => 'المنتجات',
                    'data' => $products->map(fn (TrendValue $value) => $value->aggregate),
                    'backgroundColor' => '#1e40af',
                    'borderColor' => '#0000cc',
                ],
                [
                    'label' => 'المناقصات',
                    'data' => $tender->map(fn (TrendValue $value) => $value->aggregate),
                    'backgroundColor' => '#00bb00',
                    'borderColor' => '#4ade80',
                ],
                [
                    'label' => 'الشواغر وطلبات التوظيف',
                    'data' => $job->map(fn (TrendValue $value) => $value->aggregate),
                    'backgroundColor' => '#9d174d',
                    'borderColor' => '#9f1239',
                ],
            ],
            'labels' =>  $products->map(fn (TrendValue $value) => $value->date),
        ];
    }

    protected function getType(): string
    {
        return 'line';
    }
}
