<?php

namespace App\Filament\Resources\SellerResource\Pages;

use App\Enums\PartnerTypeEnum;
use App\Filament\Resources\SellerResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateSeller extends CreateRecord
{
    protected static string $resource = SellerResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['type'] = PartnerTypeEnum::SELLER->value;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
