<?php

namespace App\Filament\Resources\SellerResource\Pages;

use App\Filament\Resources\SellerResource;
use App\Models\Product;
use App\Models\User;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListSellers extends ListRecords
{
    protected static string $resource = SellerResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    protected function getTableQuery(): ?Builder
    {
        return User::seller()
            ->select('users.id')
            ->selectSub(
                Product::selectRaw('MAX(created_at)')
                    ->whereColumn('products.user_id', 'users.id'),
                'last_product_date'
            )
            ->withCount(['products', 'followers']); // TODO: Change the autogenerated stub
    }
}
