<?php

namespace App\Filament\Resources\SellerResource\Pages;

use App\Filament\Resources\SellerResource;
use App\Models\User;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListSellers extends ListRecords
{
    protected static string $resource = SellerResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    protected function getTableQuery(): ?Builder
    {
       return User::seller()
        ->withCount(['products', 'followers'])
        ->withMax('products as last_product_date', 'created_at')
           ->where('last_product_date','>',now()->subDays(3)); // TODO: Change the autogenerated stub
    }
}
