<?php

namespace App\Filament\Resources\NewsResource\Pages;

use App\Enums\CategoryTypeEnum;
use App\Filament\Resources\NewsResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Support\Str;

class CreateNews extends CreateRecord
{
    protected static string $resource = NewsResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['expert'] = Str::words(strip_tags(html_entity_decode($data['info'])), 15);
        $data['type'] = CategoryTypeEnum::NEWS->value;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
