<?php

namespace App\Filament\Resources;

use App\Filament\Resources\AppSettingResource\Pages;
use App\Filament\Resources\AppSettingResource\RelationManagers;
use App\Models\AppSetting;
use App\Models\Setting;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class AppSettingResource extends Resource
{
    protected static ?string $model = Setting::class;
    protected static ?int $navigationSort = -2;
    protected static ?string $label = 'إعدادات التطبيق';
    protected static ?string $modelLabel = 'إعدادات التطبيق';
    protected static ?string $navigationLabel = 'إعدادات التطبيق';
    protected static ?string $pluralLabel = 'إعدادات التطبيق';
    protected static ?string $navigationGroup = 'الإعدادات';
    protected static ?string $slug = 'app-settings';

    public static function canAccess(): bool
    {
        return auth()->user()?->can('view_any_setting'); // TODO: Change the autogenerated stub
    }

    public static function canCreate(): bool
    {
        return auth()->user()?->can('create_setting') && Setting::count() === 0; // TODO: Change the autogenerated stub
    }

    public static function canDelete(Model $record): bool
    {
        return auth()->user()?->can('delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function canDeleteAny(): bool
    {
        return auth()->user()?->can('delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function canView(Model $record): bool
    {
        return auth()->user()?->can('view_any_setting'); // TODO: Change the autogenerated stub
    }

    public static function canViewAny(): bool
    {
        return auth()->user()?->can('view_any_setting'); // TODO: Change the autogenerated stub
    }

    public static function canRestoreAny(): bool
    {
        return auth()->user()?->can('restore_setting'); // TODO: Change the autogenerated stub
    }

    public static function canEdit(Model $record): bool
    {
        return auth()->user()?->can('update_setting'); // TODO: Change the autogenerated stub
    }

    public static function canForceDeleteAny(): bool
    {
        return auth()->user()?->can('force_delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function canRestore(Model $record): bool
    {
        return auth()->user()?->can('restore_setting'); // TODO: Change the autogenerated stub
    }

    public static function canForceDelete(Model $record): bool
    {
        return auth()->user()?->can('force_delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('إعدادات التطبيق')->schema([
                    Forms\Components\SpatieMediaLibraryFileUpload::make('apk')->collection('apk')->label('رفع التطبيق')->preserveFilenames(),
                    Forms\Components\Toggle::make('send_notification_hobbies')->label('حالة إشعارات الاهتمامات'),

                    Forms\Components\TextInput::make('current_version')->label('الإصدار الحالي من التطبيق')->required(),
                    Forms\Components\Toggle::make('force_upgrade')->label('حالة المطالبة بالتحديث'),
                    Forms\Components\TextInput::make('whats_msg')->nullable()->label('رسالة واتس آب'),
                    Forms\Components\TextInput::make('url_for_download.play')->url()->label('رابط تحميل من GooglePlay'),
                    Forms\Components\TextInput::make('url_for_download.up_down')->url()->label('رابط تحميل من UpToDown'),
                    Forms\Components\TextInput::make('url_for_download.direct')->url()->label('رابط تحميل مباشر'),
                    Forms\Components\Section::make('إعلان بداية التطبيق')->schema([
                        Forms\Components\Grid::make()->schema([
                            Forms\Components\SpatieMediaLibraryFileUpload::make('advice')->collection('advice')->image()->imageEditor()->imageEditorAspectRatios(['1:1', "2:1"])->label('صورة إعلان بداية التطبيق'),
                            Forms\Components\TextInput::make('advice_url')->label('رابط الإعلان')->url()->prefix('https://'),
                            Forms\Components\Toggle::make('active_advice')->label('حالة الإعلان')
                        ])->columns(2),
                        Forms\Components\Grid::make()->schema([
                            Forms\Components\Toggle::make('send_via_whatsapp')->label('إرسال رسالة التحقق بالواتسآب'),
                            Forms\Components\Toggle::make('send_via_email')->label('إرسال رسالة التحقق بالبريد')
                        ])->columns(2),
                    ])
                ]),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('current_version')->label('الإصدار الحالي من التطبيق'),
                Tables\Columns\TextColumn::make('force_upgrade')->label('حالة المطالبة بالتحديث'),
                Tables\Columns\TextColumn::make('url_for_download.play')->label('رابط تحميل من GooglePlay')->formatStateUsing(fn($state) => $state != '' ? 'زيارة' : "")->url(fn($state) => $state, true),
                Tables\Columns\TextColumn::make('url_for_download.up_down')->label('رابط تحميل من UpToDown')->formatStateUsing(fn($state) => $state != '' ? 'زيارة' : "")->url(fn($state) => $state, true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListAppSettings::route('/'),
            'create' => Pages\CreateAppSetting::route('/create'),
            'edit' => Pages\EditAppSetting::route('/{record}/edit'),
        ];
    }
}
