<?php

namespace App\Filament\Resources;

use App\Filament\Resources\ClickWhatsResource\Pages;
use App\Filament\Resources\ClickWhatsResource\RelationManagers;
use App\Models\ClickWhats;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class ClickWhatsResource extends Resource
{
    protected static ?string $model = ClickWhats::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';
    protected static ?string $label='نقرات التواصل';
    protected static ?string $navigationLabel='نقرات التواصل';
    protected static ?string $pluralLabel='نقرات التواصل';
public static function canCreate(): bool
{
    return parent::canCreate()&& false; // TODO: Change the autogenerated stub
}

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                //
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->defaultSort('created_at','desc')
            ->columns([
                Tables\Columns\TextColumn::make('user.name')->label('اسم المتواصل')->url(fn($record)=>UserResource::getUrl('edit',['record'=>$record->user_id]))->searchable(),
                Tables\Columns\TextColumn::make('seller.seller_name')->label('المتجر')->url(fn($record)=>UserResource::getUrl('edit',['record'=>$record->seller_id]))->searchable(),
                Tables\Columns\TextColumn::make('product.name')->label('المنتجات')->url(fn($record)=>ProductResource::getUrl('edit',['record'=>$record->product_id])),
                Tables\Columns\TextColumn::make('created_at')->since()->label('تاريخ التواصل'),
            ])
            ->filters([
                //
            ])
            ->actions([
//                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListClickWhats::route('/'),
            'create' => Pages\CreateClickWhats::route('/create'),
            'edit' => Pages\EditClickWhats::route('/{record}/edit'),
        ];
    }
}
