<?php

namespace App\Filament\Resources;

use App\Filament\Resources\CouponResource\Pages;
use App\Filament\Resources\CouponResource\RelationManagers;
use App\Models\Coupon;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class CouponResource extends Resource
{
    protected static ?string $model = Coupon::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';
    protected static ?int $navigationSort = 13;
    protected static ?string $label = 'كوبون';
    protected static ?string $modelLabel = 'كوبون';
    protected static ?string $navigationLabel = 'الكوبونات';
    protected static ?string $pluralLabel = 'الكوبونات';
    protected static ?string $navigationGroup = 'المستخدمين';
    public static function canEdit(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }


    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('الكوبونات')->schema([
                  Forms\Components\Fieldset::make('بيانات الكوبون')->schema([
                      Forms\Components\Placeholder::make('code')->content(fn($record) => $record?->code)->label('الكود'),
                      Forms\Components\Placeholder::make('password')->content(fn($record) => $record?->password)->label('كلمة السر'),
                      Forms\Components\Placeholder::make('price')->content(fn($record) => $record?->price)->label(' السعر'),

                  ]),
                    Forms\Components\Fieldset::make('معلومات المشتري')->schema([
                        Forms\Components\Placeholder::make('user.name')->content(fn($record) => $record?->user?->name)->label('المشتري'),
                        Forms\Components\Placeholder::make('bay_at')->content(fn($record) => $record?->bay_at)->label(' تم شراءه في'),
                        Forms\Components\Placeholder::make('used.name')->content(fn($record) => $record?->user?->name)->label('استخدمه'),
                        Forms\Components\Placeholder::make('used_at')->content(fn($record) => $record?->used_at)->label(' تم إستخدامه في'),
                    ])->visible(fn($record) => $record?->user != null)


                ])
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('price')->label(' السعر'),
                Tables\Columns\TextColumn::make('user.name')->label('المشتري'),
                Tables\Columns\TextColumn::make('bay_at')->label(' تم شراءه في'),
                Tables\Columns\TextColumn::make('used.name')->label('استخدمه'),
                Tables\Columns\TextColumn::make('used_at')->label(' تم إستخدامه في'),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListCoupons::route('/'),
            'create' => Pages\CreateCoupon::route('/create'),
            'edit' => Pages\EditCoupon::route('/{record}/edit'),
        ];
    }
}
