<?php

namespace App\Filament\Resources;

use App\Enums\IdentityEnum;
use App\Enums\OrderStatusEnum;
use App\Filament\Resources\IdentityResource\Pages;
use App\Filament\Resources\IdentityResource\RelationManagers;
use App\Models\Identity;
use App\Models\User;
use Filament\Forms;
use Filament\Forms\Components\Select;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class IdentityResource extends Resource
{
    protected static ?string $model = Identity::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';
    protected static ?string $label = 'التوثيق';
    protected static ?string $modelLabel = 'التوثيق';
    protected static ?string $navigationLabel = 'طلبات التوثيق';
    protected static ?string $pluralLabel = 'طلبات التوثيق';
    protected static ?int $navigationSort = -13;
    protected static ?string $navigationGroup = 'المستخدمين';

    public static function getNavigationBadge(): ?string
    {
        return Identity::where('status', 'pending')->count() ?? '0'; // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Select::make('user_id')
                    ->label('المستخدم')
                    ->searchable()
                    ->options(fn($state) => $state
                        ? User::where('id', $state)->pluck('name', 'id')
                        : []
                    )
                    ->getSearchResultsUsing(fn(string $search) => User::query()
                        ->where('name', 'like', "%{$search}%")
                        ->limit(10)
                        ->pluck('name', 'id')
                    )
                    ->getOptionLabelUsing(fn($value): ?string => User::find($value)?->name
                    ),
                Forms\Components\SpatieMediaLibraryFileUpload::make('front')->collection('front')->conversion('webp')->label('الوجه الأمامي')->openable(),
                Forms\Components\SpatieMediaLibraryFileUpload::make('back')->collection('back')->conversion('webp')->label('الوجه الخلفي')->openable(),
                Forms\Components\SpatieMediaLibraryFileUpload::make('passport')->collection('passport')->conversion('webp')->label('جواز سفر')->openable(),
                Forms\Components\SpatieMediaLibraryFileUpload::make('record')->collection('record')->conversion('webp')->label('سجل تجاري')->openable(),
                Forms\Components\Select::make('status')->options([
                    IdentityEnum::PENDING->value => IdentityEnum::PENDING->getLabel(),
                    IdentityEnum::COMPLETE->value => IdentityEnum::COMPLETE->getLabel(),
                    IdentityEnum::CANCELE->value => IdentityEnum::CANCELE->getLabel(),
                ])->default(IdentityEnum::PENDING->value)->required()->label('الحالة'),
                Forms\Components\Select::make('type')->options([
                    IdentityEnum::IDENTITY->value => IdentityEnum::IDENTITY->getLabel(),
                    IdentityEnum::PASSPORT->value => IdentityEnum::PASSPORT->getLabel(),
                    IdentityEnum::RECORD->value => IdentityEnum::RECORD->getLabel(),
                ])->default(IdentityEnum::IDENTITY->value)->required()->label('نوع'),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('id')->label('#'),
                Tables\Columns\TextColumn::make('user.name')->label('المستخدم')->url(fn($record)=>UserResource::getUrl('edit',['record'=>$record->user->id]),true),
                Tables\Columns\TextColumn::make('user.full_phone')->label('الهاتف')->url(fn($record)=>'https://wa.me/'.$record->user->full_phone,true),
                Tables\Columns\TextColumn::make('status')->formatStateUsing(fn($state) =>$state!=null ? IdentityEnum::tryFrom($state)?->getLabel():null)->label('الحالة'),
                Tables\Columns\SpatieMediaLibraryImageColumn::make('front')->label('الوجه الأمامي')->collection('front')->conversion('web')->url(fn($record) => $record->getFirstMediaUrl('front', 'web'), true),
                Tables\Columns\SpatieMediaLibraryImageColumn::make('back')->label('الوجه الخلفي')->collection('back')->conversion('web')->url(fn($record) => $record->getFirstMediaUrl('back', 'web'), true),
                Tables\Columns\SpatieMediaLibraryImageColumn::make('passport')->label('جواز سفر')->collection('passport')->conversion('web')->url(fn($record) => $record->getFirstMediaUrl('passport', 'web'), true),
                Tables\Columns\SpatieMediaLibraryImageColumn::make('record')->label('سجل تجاري')->collection('record')->conversion('web')->url(fn($record) => $record->getFirstMediaUrl('record', 'web'), true),
                Tables\Columns\TextColumn::make('type')
                    ->formatStateUsing(fn($state)=>$state!=null ? IdentityEnum::tryFrom($state)?->getLabel():null)->label('نوع'),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\Action::make('status')->label('توثيق الحساب')->requiresConfirmation()->action(function ($record) {
                    $record->update([
                        'status' => IdentityEnum::COMPLETE->value,
                    ]);
                })->visible(fn($record) => $record->status == 'pending'),
                Tables\Actions\Action::make('status_cancel')->label('رفض الطلب')->requiresConfirmation()->action(function ($record) {
                    $record->update([
                        'status' => IdentityEnum::CANCELE->value,
                    ]);
                })->visible(fn($record) => $record->status == 'pending'),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListIdentities::route('/'),
            'create' => Pages\CreateIdentity::route('/create'),
            'edit' => Pages\EditIdentity::route('/{record}/edit'),
        ];
    }
}
