<?php

namespace App\Filament\Resources;

use App\Filament\Resources\JobWorkerResource\Pages;
use App\Filament\Resources\JobWorkerResource\RelationManagers;
use App\Models\Job;
use App\Models\JobWorker;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class JobWorkerResource extends Resource
{
    protected static ?string $model = Job::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';
public static function canCreate(): bool
{
    return false; // TODO: Change the autogenerated stub
}

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                //
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('queue')->label('الدور'),
                Tables\Columns\TextColumn::make('payload')->label('العمل'),
            ])
            ->filters([
                //
            ])
            ->actions([

            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([

                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListJobWorkers::route('/'),
            'create' => Pages\CreateJobWorker::route('/create'),
            'edit' => Pages\EditJobWorker::route('/{record}/edit'),
        ];
    }
}
