<?php

namespace App\Filament\Resources;

use App\Filament\Resources\LoginSettingResource\Pages;
use App\Filament\Resources\LoginSettingResource\RelationManagers;
use App\Models\LoginSetting;
use App\Models\Setting;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class LoginSettingResource extends Resource
{
    protected static ?string $model = Setting::class;
    protected static ?int $navigationSort = -2;
    protected static ?string $label = 'إعدادات التسجيل بالموقع';
    protected static ?string $modelLabel = 'إعدادات التسجيل بالموقع';
    protected static ?string $navigationLabel = 'إعدادات التسجيل بالموقع';
    protected static ?string $pluralLabel = 'إعدادات التسجيل بالموقع';
    protected static ?string $navigationGroup = 'الإعدادات';
    protected static ?string $slug = 'login-settings';

    public static function canAccess(): bool
    {
        return auth()->user()?->can('view_any_setting'); // TODO: Change the autogenerated stub
    }

    public static function canCreate(): bool
    {
        return auth()->user()?->can('create_setting') && Setting::count() === 0; // TODO: Change the autogenerated stub
    }

    public static function canDelete(Model $record): bool
    {
        return auth()->user()?->can('delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function canDeleteAny(): bool
    {
        return auth()->user()?->can('delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function canView(Model $record): bool
    {
        return auth()->user()?->can('view_any_setting'); // TODO: Change the autogenerated stub
    }

    public static function canViewAny(): bool
    {
        return auth()->user()?->can('view_any_setting'); // TODO: Change the autogenerated stub
    }

    public static function canRestoreAny(): bool
    {
        return auth()->user()?->can('restore_setting'); // TODO: Change the autogenerated stub
    }

    public static function canEdit(Model $record): bool
    {
        return auth()->user()?->can('update_setting'); // TODO: Change the autogenerated stub
    }

    public static function canForceDeleteAny(): bool
    {
        return auth()->user()?->can('force_delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function canRestore(Model $record): bool
    {
        return auth()->user()?->can('restore_setting'); // TODO: Change the autogenerated stub
    }

    public static function canForceDelete(Model $record): bool
    {
        return auth()->user()?->can('force_delete_setting'); // TODO: Change the autogenerated stub
    }
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
               Forms\Components\Section::make('خيارات تسجيل الدخول / أسعار الصرف')->schema([
                    Forms\Components\Toggle::make('available_country')->label('تفعيل التسجيل من جميع البلدان'),
                    Forms\Components\Toggle::make('available_any_email')->label('تفعيل التسجيل من أي إيميل'),
                    Forms\Components\Toggle::make('auto_update_exchange')->label('تحديث سعر الصرف تلقائيا'),
                    Forms\Components\Toggle::make('active_points')->label('تفعيل نقاط التسويق بالعمولة'),
                    Forms\Components\TextInput::make('dollar_value')->label('سعر الدولار بالتركي')->nullable()->numeric(),
                    Forms\Components\TextInput::make('dollar_syr')->label('سعر الدولار بالسوري')->nullable()->numeric(),
                    Forms\Components\TextInput::make('point_value')->label('سعر النقطة بالدولار')->nullable()->numeric(),
                    Forms\Components\TextInput::make('num_point_for_register')->label('عدد النقاط لكل تسجيل')->nullable()->numeric(),
                    Forms\Components\TextInput::make('less_amount_point_pull')->label('أقل قيمة لسحب النقاط')->nullable()->numeric(),
                ]),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('dollar_value')->label('سعر الدولار بالتركي'),
                Tables\Columns\TextColumn::make('dollar_syr')->label('سعر الدولار بالسوري'),
                Tables\Columns\TextColumn::make('point_value')->label('سعر النقطة بالدولار'),
                Tables\Columns\TextColumn::make('num_point_for_register')->label('عدد النقاط لكل تسجيل'),
                Tables\Columns\TextColumn::make('less_amount_point_pull')->label('أقل قيمة لسحب النقاط'),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListLoginSettings::route('/'),
            'create' => Pages\CreateLoginSetting::route('/create'),
            'edit' => Pages\EditLoginSetting::route('/{record}/edit'),
        ];
    }
}
