<?php

namespace App\Filament\Resources;

use App\Enums\IsActiveEnum;
use App\Filament\Resources\MainCityResource\Pages;
use App\Filament\Resources\MainCityResource\RelationManagers;
use App\Models\City;
use App\Models\MainCity;
use BezhanSalleh\FilamentShield\Contracts\HasShieldPermissions;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class MainCityResource extends Resource implements HasShieldPermissions

{
    protected static ?string $model = City::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';
    protected static ?int $navigationSort = 8;
    protected static ?string $label = 'مدينة رئيسية';
    protected static ?string $modelLabel = 'مدينة رئيسية';
    protected static ?string $navigationLabel = 'المدن الرئيسية';
    protected static ?string $pluralLabel = 'المدن الرئيسية';

    protected static ?string $navigationGroup='المناطق و المواد';
    public static function getPermissionPrefixes(): array
    {
        return [
            'view_any',
            'create',
            'update',
            'delete',

            'restore',
            'force_delete'
        ];
    }

    public static function canAccess(): bool
    {
        return  auth()->user()?->can('view_any_mainCity'); // TODO: Change the autogenerated stub
    }

    public static function canCreate(): bool
    {
        return  auth()->user()?->can('create_mainCity'); // TODO: Change the autogenerated stub
    }

    public static function canDelete(Model $record): bool
    {
        return  auth()->user()?->can('delete_mainCity'); // TODO: Change the autogenerated stub
    }

    public static function canDeleteAny(): bool
    {
        return  auth()->user()?->can('delete_mainCity'); // TODO: Change the autogenerated stub
    }

    public static function canView(Model $record): bool
    {
        return  auth()->user()?->can('view_any_mainCity'); // TODO: Change the autogenerated stub
    }

    public static function canViewAny(): bool
    {
        return  auth()->user()?->can('view_any_mainCity'); // TODO: Change the autogenerated stub
    }

    public static function canRestoreAny(): bool
    {
        return  auth()->user()?->can('restore_mainCity'); // TODO: Change the autogenerated stub
    }

    public static function canEdit(Model $record): bool
    {
        return  auth()->user()?->can('update_mainCity'); // TODO: Change the autogenerated stub
    }

    public static function canForceDeleteAny(): bool
    {
        return  auth()->user()?->can('force_delete_mainCity'); // TODO: Change the autogenerated stub
    }

    public static function canRestore(Model $record): bool
    {
        return  auth()->user()?->can('restore_mainCity'); // TODO: Change the autogenerated stub
    }

    public static function canForceDelete(Model $record): bool
    {
        return  auth()->user()?->can('force_delete_mainCity'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('المدن')->schema([
                    Forms\Components\SpatieMediaLibraryFileUpload::make('image')->collection('image')->conversion('webp')->image()->imageCropAspectRatio('1:1')->label('صورة')->imageEditor(),
                    Forms\Components\TextInput::make('name')->label('اسم المدينة'),
                    Forms\Components\Toggle::make('is_delivery')->label('تفعيل التوصيل'),
                    Forms\Components\Toggle::make('is_active')->label('حالة المدينة'),
                ])
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\SpatieMediaLibraryImageColumn::make('image')->collection('image')->circular()->label('صورة'),
                Tables\Columns\TextColumn::make('name')->label('المدينة')->searchable(),
                Tables\Columns\TextColumn::make('city.name')->label('المدينة الرئيسية')->sortable(),
                Tables\Columns\TextColumn::make('is_active')->formatStateUsing(fn($state)=>IsActiveEnum::tryFrom($state)?->getLabel())->icon(fn($state)=>IsActiveEnum::tryFrom($state)?->getIcon())->color(fn($state)=>IsActiveEnum::tryFrom($state)?->getColor())->label('الحالة'),
            ])->reorderable('sortable')
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListMainCities::route('/'),
            'create' => Pages\CreateMainCity::route('/create'),
            'edit' => Pages\EditMainCity::route('/{record}/edit'),
        ];
    }
}
