<?php

namespace App\Filament\Resources;

use App\Filament\Resources\MessageMarketingResource\Pages;
use App\Filament\Resources\MessageMarketingResource\RelationManagers;
use App\Models\MessageMarketing;
use App\Models\Setting;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class MessageMarketingResource extends Resource
{
    protected static ?string $model = Setting::class;
    protected static ?int $navigationSort = 5;
    protected static ?string $label = 'رسائل التسويق';
    protected static ?string $modelLabel = 'رسائل التسويق';
    protected static ?string $navigationLabel = 'رسائل التسويق';
    protected static ?string $pluralLabel = 'رسائل التسويق';
    protected static ?string $navigationGroup = 'الإعدادات';
    protected static ?string $slug = 'msg-marketing';

    public static function canAccess(): bool
    {
        return auth()->user()?->can('view_any_setting'); // TODO: Change the autogenerated stub
    }

    public static function canCreate(): bool
    {
        return auth()->user()?->can('create_setting') && Setting::count() === 0; // TODO: Change the autogenerated stub
    }

    public static function canDelete(Model $record): bool
    {
        return auth()->user()?->can('delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function canDeleteAny(): bool
    {
        return auth()->user()?->can('delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function canView(Model $record): bool
    {
        return auth()->user()?->can('view_any_setting'); // TODO: Change the autogenerated stub
    }

    public static function canViewAny(): bool
    {
        return auth()->user()?->can('view_any_setting'); // TODO: Change the autogenerated stub
    }

    public static function canRestoreAny(): bool
    {
        return auth()->user()?->can('restore_setting'); // TODO: Change the autogenerated stub
    }

    public static function canEdit(Model $record): bool
    {
        return auth()->user()?->can('update_setting'); // TODO: Change the autogenerated stub
    }

    public static function canForceDeleteAny(): bool
    {
        return auth()->user()?->can('force_delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function canRestore(Model $record): bool
    {
        return auth()->user()?->can('restore_setting'); // TODO: Change the autogenerated stub
    }

    public static function canForceDelete(Model $record): bool
    {
        return auth()->user()?->can('force_delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('رسائل التسويق')->schema([
                    Forms\Components\Textarea::make('msg_marketing.user')->label('لا يملك منتجات')->required(),
                    Forms\Components\Textarea::make('msg_marketing.market_5')->label('1 -> 5 منتجات')->required(),
                    Forms\Components\Textarea::make('msg_marketing.market_20')->label('6 -> 20 منتجات')->required(),
                    Forms\Components\Textarea::make('msg_marketing.market_50')->label('21 -> 50 منتجات')->required(),
                    Forms\Components\Textarea::make('msg_marketing.market_100')->label('أكثر من 100')->required(),
                    Forms\Components\Textarea::make('msg_marketing.followers')->label('رسالة متابعة جديدة')
                        ->hint('ضع علامةيتابعك [user]، سيتلقى إشعارًا فور نشرك لمنتج جديد ....')
                        ->required(),
                ])
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('msg_marketing.user')->label('لا يملك منتجات'),
                Tables\Columns\TextColumn::make('msg_marketing.market_5')->label('1 -> 5 منتجات'),
                Tables\Columns\TextColumn::make('msg_marketing.market_20')->label('6 -> 20 منتجات'),
                Tables\Columns\TextColumn::make('msg_marketing.market_50')->label('21 -> 50 منتجات'),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
//                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListMessageMarketings::route('/'),
            'create' => Pages\CreateMessageMarketing::route('/create'),
            'edit' => Pages\EditMessageMarketing::route('/{record}/edit'),
        ];
    }
}
