<?php

namespace App\Filament\Resources;

use App\Filament\Resources\PrivacyResource\Pages;
use App\Filament\Resources\PrivacyResource\RelationManagers;
use App\Models\Privacy;
use App\Models\Setting;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class PrivacyResource extends Resource
{
    protected static ?string $model = Setting::class;


    protected static ?int $navigationSort = -2;
    protected static ?string $label = 'من نحن & سياسة الخصوصية';
    protected static ?string $modelLabel = 'من نحن & سياسة الخصوصية';
    protected static ?string $navigationLabel = 'من نحن & سياسة الخصوصية';
    protected static ?string $pluralLabel = 'من نحن & سياسة الخصوصية';
    protected static ?string $navigationGroup = 'الإعدادات';
    protected static ?string $slug = 'about-privacy';

    public static function canAccess(): bool
    {
        return auth()->user()?->can('view_any_setting'); // TODO: Change the autogenerated stub
    }

    public static function canCreate(): bool
    {
        return auth()->user()?->can('create_setting') && Setting::count() === 0; // TODO: Change the autogenerated stub
    }

    public static function canDelete(Model $record): bool
    {
        return auth()->user()?->can('delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function canDeleteAny(): bool
    {
        return auth()->user()?->can('delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function canView(Model $record): bool
    {
        return auth()->user()?->can('view_any_setting'); // TODO: Change the autogenerated stub
    }

    public static function canViewAny(): bool
    {
        return auth()->user()?->can('view_any_setting'); // TODO: Change the autogenerated stub
    }

    public static function canRestoreAny(): bool
    {
        return auth()->user()?->can('restore_setting'); // TODO: Change the autogenerated stub
    }

    public static function canEdit(Model $record): bool
    {
        return auth()->user()?->can('update_setting'); // TODO: Change the autogenerated stub
    }

    public static function canForceDeleteAny(): bool
    {
        return auth()->user()?->can('force_delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function canRestore(Model $record): bool
    {
        return auth()->user()?->can('restore_setting'); // TODO: Change the autogenerated stub
    }

    public static function canForceDelete(Model $record): bool
    {
        return auth()->user()?->can('force_delete_setting'); // TODO: Change the autogenerated stub
    }


    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('الإعدادات')->schema([
                    Forms\Components\Wizard::make([
                        Forms\Components\Wizard\Step::make('من نحن')->schema([
                            Forms\Components\RichEditor::make('about')->nullable()->label('عن التطبيق'),
                        ]),

                        Forms\Components\Wizard\Step::make('سياسة الخصوصية')->schema([
                            Forms\Components\RichEditor::make('privacy')->nullable()->label('سياسة الخصوصية'),
                        ]),
                    ])->skippable()
                    ])

                    ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                //
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListPrivacies::route('/'),
            'create' => Pages\CreatePrivacy::route('/create'),
            'edit' => Pages\EditPrivacy::route('/{record}/edit'),
        ];
    }
}
