<?php

namespace App\Filament\Resources;

use App\Enums\CategoryTypeEnum;
use App\Enums\OrderStatusEnum;
use App\Enums\ProductActiveEnum;
use App\Filament\Resources\ServiceResource\Pages;
use App\Filament\Resources\ServiceResource\RelationManagers;
use App\Helpers\HelperMedia;
use App\Models\Category;
use App\Models\City;
use App\Models\Product;
use App\Models\Service;
use App\Models\User;
use BezhanSalleh\FilamentShield\Contracts\HasShieldPermissions;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class ServiceResource extends Resource implements HasShieldPermissions
{
    protected static ?string $model = Product::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';
    protected static ?string $label = 'خدمة';
    protected static ?string $modelLabel = 'خدمة';
    protected static ?string $navigationLabel = 'الخدمات';
    protected static ?string $pluralLabel = 'الخدمات';
    protected static ?int $navigationSort = -15;
    protected static ?string $navigationGroup = 'العروض';
    protected static ?string $slug='services';
// permissions
    public static function getPermissionPrefixes(): array
    {
        return [
            'view_any',
            'create',
            'update',
            'delete',

            'restore',
            'force_delete'
        ];
    }

        public static function canAccess(): bool
    {
        return  auth()->user()?->can('view_any_service'); // TODO: Change the autogenerated stub
    }

    public static function canCreate(): bool
    {
        return  auth()->user()?->can('create_service'); // TODO: Change the autogenerated stub
    }

    public static function canDelete(Model $record): bool
    {
        return  auth()->user()?->can('delete_service'); // TODO: Change the autogenerated stub
    }

    public static function canDeleteAny(): bool
    {
        return  auth()->user()?->can('delete_service'); // TODO: Change the autogenerated stub
    }

    public static function canView(Model $record): bool
    {
        return  auth()->user()?->can('view_any_service'); // TODO: Change the autogenerated stub
    }

    public static function canViewAny(): bool
    {
        return  auth()->user()?->can('view_any_service'); // TODO: Change the autogenerated stub
    }

    public static function canRestoreAny(): bool
    {
        return  auth()->user()?->can('restore_service'); // TODO: Change the autogenerated stub
    }

    public static function canEdit(Model $record): bool
    {
        return  auth()->user()?->can('update_service'); // TODO: Change the autogenerated stub
    }

    public static function canForceDeleteAny(): bool
    {
        return  auth()->user()?->can('force_delete_service'); // TODO: Change the autogenerated stub
    }

    public static function canRestore(Model $record): bool
    {
        return  auth()->user()?->can('restore_service'); // TODO: Change the autogenerated stub
    }

    public static function canForceDelete(Model $record): bool
    {
        return  auth()->user()?->can('force_delete_service'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationBadge(): ?string
    {
        return (string)Product::service()->where('active',OrderStatusEnum::PENDING->value)->count();
    }
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('الخدمات')->schema([
                    HelperMedia::getFileUpload(),
                    Forms\Components\Select::make('user_id')->options(User::seller()->pluck('users.seller_name', 'users.id'))->label('المتجر')->live()->afterStateUpdated(fn($set, $state) => $set('city_id', User::find($state)?->city_id)),
                    Forms\Components\Select::make('city_id')->options(City::pluck('name', 'id'))->searchable()->label('المدينة'),
                    Forms\Components\TextInput::make('name')->label('اسم الخدمة'),
                    Forms\Components\RichEditor::make('info')->label('وصف الخدمة'),
                    Forms\Components\TagsInput::make('tags')->suggestions(fn() => Product::service()->pluck('tags')->flatten()->unique())->label('تاغات'),
                    Forms\Components\Select::make('category_id')->options(Category::service()->pluck('name', 'id'))->label('يتبع القسم')->searchable()->live()->required(),
                    Forms\Components\Select::make('sub1_id')->options(fn($get) => Category::find($get('category_id'))?->children?->pluck('name', 'id'))->label('يتبع القسم')->searchable()->live(),

                    Forms\Components\TextInput::make('url')->label('رابط الخدمة'),
                    Forms\Components\TextInput::make('address')->label('العنوان التفصيلي'),
                    Forms\Components\TextInput::make('phone')->label('رقم الهاتف'),
                    Forms\Components\TextInput::make('email')->label('البريد الإلكتروني')->email(),
                    Forms\Components\Radio::make('active')->options([
                        ProductActiveEnum::PENDING->value => ProductActiveEnum::PENDING->getLabel(),
                        ProductActiveEnum::ACTIVE->value => ProductActiveEnum::ACTIVE->getLabel(),
                        ProductActiveEnum::BLOCK->value => ProductActiveEnum::BLOCK->getLabel(),
                    ])->label('حالة الخدمة')->default(ProductActiveEnum::PENDING->value),

                ])
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->modifyQueryUsing(fn($query) => $query->service())
            ->columns([
                Tables\Columns\TextColumn::make('id')->label('رقم المنتج')->searchable(),
                Tables\Columns\TextColumn::make('name')->label('اسم المنتج')->description(fn($record) => $record->expert),
                Tables\Columns\TextColumn::make('category.name')->label('القسم الرئيسي'),
                Tables\Columns\TextColumn::make('sub1.name')->label('القسم الفرعي'),
                Tables\Columns\TextColumn::make('city.name')->label('المدينة'),
                Tables\Columns\TextColumn::make('user.name')->label('المتجر')->url(fn($record) => $record->user_id!=null ?UserResource::getUrl('edit', ['record' => $record->user_id]):null),
                Tables\Columns\TextColumn::make('views_count')->label('عدد المشاهدات'),
                Tables\Columns\TextColumn::make('created_at')->since()->label('أضيف منذ'),
                Tables\Columns\TextColumn::make('active')->formatStateUsing(fn($state)=>ProductActiveEnum::tryFrom($state)?->getLabel())->color(fn($state)=>ProductActiveEnum::tryFrom($state)?->getColor())->icon(fn($state)=>ProductActiveEnum::tryFrom($state)?->getIcon())->label('الحالة'),

            ])
            ->filters([
               Tables\Filters\Filter::make('filter')->form([
                   Forms\Components\Select::make('category_id')->options(Category::where('is_main',true)->where('type',CategoryTypeEnum::SERVICE->value)->pluck('name','id'))->live()->label('القسم الرئيسي'),
                   Forms\Components\Select::make('sub1_id')->options(fn($get)=>Category::find($get('category_id'))?->children->pluck('name','id'))->label('القسم الفرعي'),
               ])->query(fn($query,$data)=>$query
               ->when($data['category_id'],fn($query)=>$query->where('category_id',$data['category_id']))
               ->when($data['sub1_id'],fn($query)=>$query->where('sub1_id',$data['sub1_id']))
               )
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
                Tables\Actions\RestoreAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                    Tables\Actions\ForceDeleteBulkAction::make(),
                    Tables\Actions\BulkAction::make('set_category')
                        ->form([
                            Forms\Components\Select::make('category_id')->options(Category::service()->pluck('name', 'id'))->label('يتبع القسم')->searchable()->live()->required(),

                            Forms\Components\Select::make('sub1_id')->options(fn($get) => Category::find($get('category_id'))?->children?->pluck('name', 'id'))->label('يتبع القسم')->searchable()->live(),
                        ])
                        ->action(function($records,$data){
                            Product::whereIn('id',$records->pluck('id')->toArray())->update([
                                'category_id'=>$data['category_id'],
                                'sub1_id'=>$data['sub1_id']
                                ]);
                        })->label('تحديد القسم')
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListServices::route('/'),
            'create' => Pages\CreateService::route('/create'),
            'edit' => Pages\EditService::route('/{record}/edit'),
        ];
    }
}
