<?php

namespace App\Filament\Resources;

use App\Filament\Resources\SocialResource\Pages;
use App\Filament\Resources\SocialResource\RelationManagers;
use App\Models\Setting;
use App\Models\Social;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class SocialResource extends Resource
{
    protected static ?string $model = Setting::class;


    protected static ?int $navigationSort = -2;
    protected static ?string $label = 'مواقع التواصل';
    protected static ?string $modelLabel = 'مواقع التواصل';
    protected static ?string $navigationLabel = 'مواقع التواصل';
    protected static ?string $pluralLabel = 'مواقع التواصل';
    protected static ?string $navigationGroup = 'الإعدادات';
    protected static ?string $slug = 'social-media';

    public static function canAccess(): bool
    {
        return auth()->user()?->can('view_any_setting'); // TODO: Change the autogenerated stub
    }

    public static function canCreate(): bool
    {
        return auth()->user()?->can('create_setting') && Setting::count() === 0; // TODO: Change the autogenerated stub
    }

    public static function canDelete(Model $record): bool
    {
        return auth()->user()?->can('delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function canDeleteAny(): bool
    {
        return auth()->user()?->can('delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function canView(Model $record): bool
    {
        return auth()->user()?->can('view_any_setting'); // TODO: Change the autogenerated stub
    }

    public static function canViewAny(): bool
    {
        return auth()->user()?->can('view_any_setting'); // TODO: Change the autogenerated stub
    }

    public static function canRestoreAny(): bool
    {
        return auth()->user()?->can('restore_setting'); // TODO: Change the autogenerated stub
    }

    public static function canEdit(Model $record): bool
    {
        return auth()->user()?->can('update_setting'); // TODO: Change the autogenerated stub
    }

    public static function canForceDeleteAny(): bool
    {
        return auth()->user()?->can('force_delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function canRestore(Model $record): bool
    {
        return auth()->user()?->can('restore_setting'); // TODO: Change the autogenerated stub
    }

    public static function canForceDelete(Model $record): bool
    {
        return auth()->user()?->can('force_delete_setting'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('الإعدادات العامة')->schema([
                    Forms\Components\Fieldset::make('معلومات مواقع التواصل')->schema([
                        Forms\Components\TextInput::make('social.twitter')->label('رابط تويتر')->nullable()->url()->placeholder('https://'),
                        Forms\Components\TextInput::make('social.face')->label('رابط فيسبوك')->nullable()->url()->placeholder('https://'),
                        Forms\Components\TextInput::make('social.instagram')->label('رابط إنستغرام')->nullable()->url()->placeholder('https://'),
                        Forms\Components\TextInput::make('social.youtube')->label('رابط يوتيوب')->nullable()->url()->placeholder('https://'),
                        Forms\Components\TextInput::make('social.linkedin')->label('رابط لينكدن')->nullable()->url()->placeholder('https://'),
                        Forms\Components\TextInput::make('social.telegram')->label('رابط تلغرام')->nullable()->url()->placeholder('https://'),
                    ]),
                    Forms\Components\Fieldset::make('إعدادات عامة')->schema([
                        Forms\Components\SpatieMediaLibraryFileUpload::make('logo')->collection('logo')->conversion('webp')->label('أيقونة الموقع')->image()->imageCropAspectRatio('1:1')->imageEditor(),
                        Forms\Components\SpatieMediaLibraryFileUpload::make('white-logo')->collection('white-logo')->conversion('webp')->label('لوغو الفوتر')->image()->imageCropAspectRatio('1:1')->imageEditor(),
                        Forms\Components\TextInput::make('social.name')->label('اسم الموقع'),
                        Forms\Components\TextInput::make('social.email')->label('بريد الموقع الرئيسي')->nullable()->email(),
                        Forms\Components\TextInput::make('social.sub_email')->label('بريد الموقع الثانوي')->nullable()->email(),
                        Forms\Components\TextInput::make('social.phone')->label('الهاتف الرئيسي'),
                        Forms\Components\TextInput::make('social.sub_phone')->label('الهاتف الثانوي'),

                        Forms\Components\TextInput::make('address')->label('العنوان'),
                        Forms\Components\TextInput::make('longitude')->label('خط الطول')->nullable()->numeric(),
                        Forms\Components\TextInput::make('latitude')->label('خط العرض')->nullable()->numeric(),
                        Forms\Components\TextInput::make('weather_api')->label('Api الطقس')->nullable(),
                        Forms\Components\Select::make('plan_id')->relationship('plan', 'name')->searchable()->preload()->label('الخطة الإفتراضية للمستخدمين الجدد'),

                    ])
                ]),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('social.twitter')->formatStateUsing(fn($state)=>$state!=''?'زيارة':'')->label(' تويتر')->url(fn($state)=>$state),
                Tables\Columns\TextColumn::make('social.face')->formatStateUsing(fn($state)=>$state!=''?'زيارة':'')->label(' فيسبوك')->url(fn($state)=>$state),
                Tables\Columns\TextColumn::make('social.instagram')->formatStateUsing(fn($state)=>$state!=''?'زيارة':'')->label(' إنستغرام')->url(fn($state)=>$state),
                Tables\Columns\TextColumn::make('social.youtube')->formatStateUsing(fn($state)=>$state!=''?'زيارة':'')->label(' يوتيوب')->url(fn($state)=>$state),
                Tables\Columns\TextColumn::make('social.linkedin')->formatStateUsing(fn($state)=>$state!=''?'زيارة':'')->label(' لينكدن')->url(fn($state)=>$state),
                Tables\Columns\TextColumn::make('social.telegram')->formatStateUsing(fn($state)=>$state!=''?'زيارة':'')->label(' تلغرام')->url(fn($state)=>$state),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListSocials::route('/'),
            'create' => Pages\CreateSocial::route('/create'),
            'edit' => Pages\EditSocial::route('/{record}/edit'),
        ];
    }
}
