<?php

namespace App\Filament\Resources;

use App\Enums\PlansDurationEnum;
use App\Filament\Resources\SubscriptionResource\Pages;
use App\Filament\Resources\SubscriptionResource\RelationManagers;
use App\Models\Plan;
use App\Models\PlanUser;
use App\Models\Subscription;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class SubscriptionResource extends Resource
{
    protected static ?string $model = PlanUser::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';
    protected static ?string $label = "الخدمات المدفوعة";
    protected static ?int $navigationSort = -1;
public static function canCreate(): bool
{
    return false; // TODO: Change the autogenerated stub
}
public static function canEdit(Model $record): bool
{
    return false; // TODO: Change the autogenerated stub
}

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                //
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->defaultSort('subscription_date', 'desc')
            ->modifyQueryUsing(function ($query) {
                return $query->whereHas('plan', function ($q) {
                    $q->whereNot('duration', PlansDurationEnum::FREE->value); // أو أي شرط يدل على أنها ليست مجانية
                });
            })
            ->columns([
                Tables\Columns\TextColumn::make('user.name')->label('المستخدم')->url(fn($record) => UserResource::getUrl('edit', ['record' => $record->user->id])),
                Tables\Columns\TextColumn::make('plan.name')->label('الخطة')->url(fn($record) => PlanResource::getUrl('edit', ['record' => $record->plan->id])),
                Tables\Columns\TextColumn::make('subscription_date')->label('بداية الإشتراك')->date('Y-m-d'),
                Tables\Columns\TextColumn::make('expired_date')->label('نهاية الإشتراك')->date('Y-m-d'),
            ])
            ->filters([
                //
            ])
            ->actions([

            ])
            ->bulkActions([

            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListSubscriptions::route('/'),

        ];
    }
}
