<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Plan extends Model
{
    use HasFactory;

    protected $guarded = [];
    protected $casts = [
        'items' => 'array',
        'options' => 'array'
    ];

    protected $withCount=[
        'users'
    ];
    protected static function booted()
    {
        self::addGlobalScope('sort',fn($query)=>$query->orderBy('sortable'));
        parent::booted(); // TODO: Change the autogenerated stub
    }
    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class);
    }
}
