<?php

namespace App\Models;

use App\Observers\PointObserve;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Point extends Model
{
    use HasFactory;

    protected $guarded = [];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::observe(PointObserve::class);
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
