<?php

namespace App\Models;

use App\Enums\CategoryTypeEnum;
use App\Enums\ProductActiveEnum;
use App\Observers\ProductObserve;
use App\Traits\MediaTrait;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Scout\Searchable;
use Spatie\MediaLibrary\HasMedia;

class Product extends Model implements HasMedia
{
    use HasFactory, MediaTrait, Searchable, SoftDeletes;

    protected $guarded = [];
    protected $casts = [
        'tags' => 'array',
        'start_date' => 'datetime',
        'end_date' => 'datetime',
        'price' => 'double'
    ];
    protected $withCount = [
        'likes',
        'comments',
        'clicks'

    ];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::observe(ProductObserve::class);
    }

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::addGlobalScope('views_sum', function (Builder $builder) {
            $builder->withSum('views', 'count');
        });
    }

    public function clicks(): HasMany
    {
        return $this->hasMany(ClickWhats::class,'product_id');
    }
    /**
     * Get the indexable data array for the model.
     *
     * @return array<string, mixed>
     */
    public function toSearchableArray(): array
    {
        return [
            'id' => (string)$this->id,
            'name' => $this->name,
            'info' => $this->info,
            'tags' => $this->tags,
        ];
    }
    public function scopeUpTo20($query)
    {
       return $query->where('power','>=',20);
    }

    public function searchableAs()
    {
        return 'search_post';
    }
    public function scopeActive($query)
    {
        return $query->where('active', ProductActiveEnum::ACTIVE->value);
    }

    public function scopePending($query)
    {
        return $query->where('active', ProductActiveEnum::PENDING->value);
    }

    public function scopeNotPending($query)
    {
        return $query->where('active', '!=', ProductActiveEnum::PENDING->value);
    }
    public function scopeBlock($query)
    {
        return $query->where('active',  ProductActiveEnum::BLOCK->value);
    }

    public function scopeProduct($query)
    {
        return $query->where('type', CategoryTypeEnum::PRODUCT->value)->orWhere('type', CategoryTypeEnum::RESTAURANT->value);
    }

    public function scopeJob($query)
    {
        return $query->where('type', CategoryTypeEnum::JOB->value)->orWhere('type', CategoryTypeEnum::SEARCH_JOB->value);
    }

    public function scopeTender($query)
    {
        return $query->where('type', CategoryTypeEnum::TENDER->value);
    }

    public function scopeNews($query)
    {
        return $query->where('type', CategoryTypeEnum::NEWS->value);
    }

    public function scopeService($query)
    {
        return $query->where('type', CategoryTypeEnum::SERVICE->value);
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    public function sub1(): BelongsTo
    {
        return $this->belongsTo(Category::class, 'sub1_id', 'id');
    }

    public function sub2(): BelongsTo
    {
        return $this->belongsTo(Category::class, 'sub2_id');
    }

    public function sub3(): BelongsTo
    {
        return $this->belongsTo(Category::class, 'sub3_id');
    }

    public function sub4(): BelongsTo
    {
        return $this->belongsTo(Category::class, 'sub4_id');
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function city(): BelongsTo
    {
        return $this->belongsTo(City::class);
    }

    public function attributeProduct(): HasMany
    {
        return $this->hasMany(AttributeProduct::class);
    }

    public function attributes(): BelongsToMany
    {
        return $this->belongsToMany(Attribute::class, 'attribute_products', 'product_id');
    }

    public function views(): HasMany
    {
        return $this->hasMany(ProductView::class, 'product_id');
    }

    public function colors(): BelongsToMany
    {
        return $this->belongsToMany(Color::class);
    }

   public function getViewsCountAttribute(): int
    {
        return $this->views->sum('count');
    }

    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class)->whereNull('comment_id')->latest();
    }

    public function rates(): HasMany
    {
        return $this->hasMany(Rate::class, 'product_id');
    }

    public function likes(): HasMany
    {
        return $this->hasMany(Like::class);
    }

    public  function getTurkeyPrice()
    {
        $usd=Setting::first()->dollar_value??35;
        return [
            "price"=>$this->price*$usd,
            "discount"=>$this->discount*$usd,
        ];
    }
    public  function getSyrPrice()
    {
        $usd=Setting::first()->dollar_syr??14750;
        return [
            "price"=>$this->price*$usd,
            "discount"=>$this->discount*$usd,
        ];
    }

    public function getPrice(){
        if($this->is_discount){
            return $this->discount;
        }
        return $this->price;
    }

    public function getIsLikeAttribute(){
        if(!auth()->check()){
            return false;
        }
        return $this->likes()->where('user_id',auth()->id())->exists();
    }

}
