<?php

namespace App\Filament\Resources\PartnerResource\Pages;

use App\Enums\PartnerTypeEnum;
use App\Filament\Resources\PartnerResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreatePartner extends CreateRecord
{
    protected static string $resource = PartnerResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['type'] = PartnerTypeEnum::PARTNER->value;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
